# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QPixmap, QImage, QFont
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, QObject
from pdf_reader import PDFHandler
from PIL.ImageQt import ImageQt
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog, QFontDialog
from pathlib import Path
import re
import copy
import json
import os

ui2 = None


class GirisEkrani(object):
    def setupUi(self, MainWindow):
        self.mw = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        ##############################################################

        self.file_path = None
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_3.clicked.connect(self.clicked_dosyaSec)
        self.pushButton.clicked.connect(self.clicked_once)
        self.pushButton_2.clicked.connect(self.clicked_sonra)

        self.pushButton.setDisabled(True)
        self.pushButton_2.setDisabled(True)

    def render_page(self):
        pix = self.pdf.toImage()
        image = QImage(pix.samples,
                       pix.width, pix.height,
                       pix.stride,
                       QImage.Format_RGB888)

        self.label.setPixmap(QPixmap.fromImage(image))
        self.label_2.setText("Sayfa: " + str(self.pdf.current_page + 1))

    def clicked_once(self):
        self.pdf.prevPage()
        self.render_page()

    def clicked_sonra(self):
        self.pdf.nextPage()
        self.render_page()

    def check_file(self):
        self.file_name = os.path.splitext(os.path.basename(self.file_path))[0]+".json" #str(os.path.basename(self.file_path)).split(".")[0] + ".json"
        print(self.file_name)
        return self.file_name in os.listdir('./')

    def clicked_dosyaSec(self):

        if self.file_path is None:
            options = QFileDialog.Options()
            fname = QFileDialog.getOpenFileName(QtWidgets.QMainWindow(), "QFileDialog.getOpenFileName()", "",
                                                "PDF Files (*.pdf)", options=options)
            self.pushButton_3.setText("Sayfayı Seç")
            self.file_path = fname[0]
            if not self.check_file():
                self.pdf = PDFHandler(self.file_path)
                self.render_page()
                self.pushButton.setDisabled(False)
                self.pushButton_2.setDisabled(False)
            else:
                self.handle_json()
                ui2.setupUi(self.index, self.sentences, self.labels, self.original_sentences, self.file_name)
                ui2.show()
                self.mw.hide()

            ## Dosya varsa yapılacak işlemler
        else:
            self.handle_pdf()
            ui2.setupUi(self.index, self.sentences, self.labels, self.original_sentences, self.file_name)
            ui2.show()
            self.mw.hide()

    def handle_json(self):
        self.sentences = []
        self.labels = []
        self.original_sentences = []

        with open(self.file_name, "r", encoding='utf8') as f:
            d = json.loads(f.read())
            self.index = d["last_index"]
            for item in d["data"]:
                self.sentences.append(item["edited_sentence"])
                self.labels.append(item["label"])
                self.original_sentences.append(item["original_sentence"])

    def handle_pdf(self):
        pattern=r"\. |\? |\! |\.\.\. |\s\."
        self.index = 0
        text = self.pdf.toText()
        self.sentences = re.split(pattern, text)
        terminators = re.findall(pattern, text)
        for idx, term in enumerate(terminators):
            self.sentences[idx] += term
        will_delete = []
        for idx, sentence in enumerate(self.sentences):
            if len(sentence.replace(" ", "").replace("\n", "")) < 1:
                will_delete.append(idx)
        i = 0
        for idx in will_delete:
            self.sentences.pop(idx - i)
            i += 1
        nofs = len(self.sentences)
        self.original_sentences = self.sentences.copy()
        self.labels = [""] * nofs
        print(nofs)
        
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Select where to start"))
        MainWindow.setWindowIcon(QtGui.QIcon('./config/logo.png'))
        self.pushButton_3.setText(_translate("MainWindow", "Dosya Seç"))
        self.pushButton.setText(_translate("MainWindow", "Önceki Sayfa"))
        self.pushButton_2.setText(_translate("MainWindow", "Sonraki Sayfa"))
        self.label_2.setText(_translate("MainWindow", "Sayfa:"))


class EtiketlemeEkrani(object):
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow

    def show(self):
        self.MainWindow.setFixedSize(640,480)
        self.MainWindow.setWindowTitle("Text Labeller")
        self.MainWindow.setWindowIcon(QtGui.QIcon('./config/logo.png'))
        self.MainWindow.show()

    def setupPdf(self, index, sentences, labels, original_sentences):
        self.index = index
        self.sentences = sentences
        self.labels = labels
        self.original_sentences = original_sentences
        self.num_of_sentences = len(self.sentences)


    def setupUi(self, index, sentences, labels, original_sentences, file_path):
        self.setupPdf(index, sentences, labels, original_sentences)
        MainWindow = self.MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.label_original_sentence = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.label_original_sentence.setDisabled(True)
        self.gridLayout.addWidget(self.label_original_sentence, 0, 1, 1, 5)
        self.label_original_sentence.setFont(QFont("Times", 14))

        self.label_original_sentence.setMaximumWidth(600)

        self.label_duygu = QtWidgets.QLabel(self.centralwidget)
        self.gridLayout.addWidget(self.label_duygu, 2, 0, 1, 1)
        self.label_duygu.setMaximumWidth(100)
        myFont = QtGui.QFont()
        myFont.setBold(True)
        self.label_duygu.setFont(myFont)
        self.label_duygu.setAlignment(QtCore.Qt.AlignCenter)


        self.plainTextEdit_cumle = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_cumle.setObjectName("plainTextEdit_cumle")
        self.plainTextEdit_cumle.setMaximumWidth(600)
        self.plainTextEdit_cumle.setFont(QFont("Times", 14))
        self.gridLayout.addWidget(self.plainTextEdit_cumle, 1, 1, 2, 5)

        self.pushButton_geri = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_geri.setObjectName("pushButton_geri")
        self.gridLayout.addWidget(self.pushButton_geri, 1, 0, 1, 1)
        self.pushButton_geri.clicked.connect(self.clicked_geri)

        self.label_blank1 = QtWidgets.QLabel(self.centralwidget)
        self.label_blank1.setText("")
        self.label_blank1.setObjectName("label_blank1")
        self.gridLayout.addWidget(self.label_blank1, 0, 1, 1, 5)
        self.label_blank0 = QtWidgets.QLabel(self.centralwidget)
        self.label_blank0.setText("")
        self.label_blank0.setObjectName("label_blank0")
        self.gridLayout.addWidget(self.label_blank0, 2, 1, 1, 5)
        with open("./config/labels.json", "r", encoding='utf8') as f:
            d = json.loads(f.read())
            duygular = d["labels"]
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_geri.setText(_translate("MainWindow", "Geri"))
        for idx, duygu in enumerate(duygular):
            # print(idx, duygu)
            button = QtWidgets.QPushButton(self.centralwidget)
            button.setObjectName(duygu + "_button")
            button.clicked.connect(lambda a, d=duygu: self.save_and_next(d))
            button.setText(_translate("MainWindow", duygu))
            self.gridLayout.addWidget(button, idx // 7 + 3, idx % 7, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.file_path = file_path
        self.plainTextEdit_cumle.setPlainText(self.sentences[self.index])
        self.label_original_sentence.setPlainText(self.original_sentences[self.index])
        self.label_duygu.setText(self.labels[self.index])

    def show_next_sentence(self):
        if self.num_of_sentences > self.index:
            self.index += 1
            self.plainTextEdit_cumle.setPlainText(self.sentences[self.index])
            self.label_original_sentence.setPlainText(self.original_sentences[self.index])
            self.label_duygu.setText(self.labels[self.index])

    def show_previous_sentence(self):
        if self.index > 0:
            self.index -= 1
            self.plainTextEdit_cumle.setPlainText(self.sentences[self.index])
            self.label_original_sentence.setPlainText(self.original_sentences[self.index])
            self.label_duygu.setText(self.labels[self.index])

    def save_label(self, label):
        self.labels[self.index] = label
        self.sentences[self.index] = self.plainTextEdit_cumle.toPlainText()
        self.save_to_file()

    def save_and_next(self, val):
        if val != "Geç":
            self.save_label(val)
        self.show_next_sentence()

    def clicked_geri(self):
        self.show_previous_sentence()

    def save_to_file(self):
        with open(self.file_path, "w+", encoding='utf8') as f:
            data = []
            for label, sentence, original_sentence in zip(self.labels, self.sentences, self.original_sentences):
                data.append({
                    "original_sentence": original_sentence,
                    "edited_sentence": sentence,
                    "label": label
                })
            data = {
                "data": data,
                "last_index": self.index + 1
            }
            json.dump(data, f, ensure_ascii=False)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = GirisEkrani()
    ui.setupUi(MainWindow)

    mw2 = QtWidgets.QMainWindow()
    ui2 = EtiketlemeEkrani(mw2)

    MainWindow.show()
    sys.exit(app.exec_())